Metrics/BlockLength:
  Exclude:
    - jwt-ext.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
