language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.3.1
  - 2.3.0
  - 2.2.6
  - 2.1.10
  - 2.1.9
addons:
  code_climate:
    repo_token:
      secure: T5j8mRouYwjc9DdAYm0Xn0rf0bSbgW+q5XgfXZhWsEk91z9jZhaot6CG4qsJxaxrdOxtptOwvF41wYt7mdW1vPaujrymuatB3bFGuR0rrUEz55wf+q8jaOaoWIKNFxV4n5eb64gIeF60ScmlVRPON4CJgGyLd11X3aF6o39mIDoJFC2ca19sw1HLH4iFXZLMnQ2WbGobeq5wTYzlSgHEIhPQiUt3z2+yEMV+qmHv896+qnfBMfrZuGn95/oByX+iF2nM7wsOHDOoeBDiidbY/mZdhkbGCw2SDwZ0SFlwzIOw+rlKUBlRy5GqqhDG0HG3uDho0oWnpM8gNK48lbY7DPVR21kb4KFaAf5gFMjsO5VIsldUQm+m0IBeSvecWhV/38ATUkmZTBx1KPm7tZeKrpq6f7u1Ujk6LqwFpPkrnRnq/+eFQCuxTCZa9CfcjUeHeKg1WlvMyKysj0LI0vgRwV/64/exEIvkXWby041nucNyvGzU+IZ2ApLrJtgxXiPXnnrlHEIE66UobzlFZhgo46KhGf2MayZuhtouLJtf1b3xYe4E/jLgh/PJk0J9ZyHK1L4x4cT7Tz2R3IsRXQPyT+ufqEqQ1PL3O1DBjy1Ob3aT+kXWwpS4flbvIdI8ziUwAW6GVK+ZD57qrcN0pcvmPmHCLISIQe/dA93/SpfS1JE=
before_install:
  - gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter
